services:
  db:
    build: './.docker/mysql'
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/init:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    security_opt:
      - seccomp:unconfined
    ports:
      - "3330:3306"
  php: # docker-compose run php bash
    build: './.docker/php'
    ports:
      - "8888:80"
    tty: true
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./:/var/www/html/
      - ./.docker/php/logs/access.log:/var/log/apache2/access.log
      - ./.docker/php/logs/error.log:/var/log/apache2/error.log
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - db
  composer: # docker-compose run composer bash
    build: './.docker/composer'
    tty: true
    command: ["composer", "install"]
    volumes:
      - ./:/app/
      - ./.docker/composer/tmp/:/tmp/
    depends_on:
      - php