CREATE DATABASE IF NOT EXISTS `my_db`;
CREATE DATABASE IF NOT EXISTS `my_db_test`;
CREATE DATABASE IF NOT EXISTS `nest_events`;

CREATE USER 'admin'@'172.24.0.1' IDENTIFIED BY 'admin';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%';