CREATE DATABASE IF NOT EXISTS my_db;
CREATE DATABASE IF NOT EXISTS my_db_test;
CREATE DATABASE IF NOT EXISTS my_db_test_1;

CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%';